routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
	$log = new App\Log();
	$log->ip = $_SERVER['REMOTE_ADDR'];
	$log->userAgent = $_SERVER['HTTP_USER_AGENT'];
	$log->save();

	$periodoSistema = App\Periodo::all()->first();
	$esAccesible = Carbon\Carbon::now()->between(Carbon\Carbon::parse(App\Periodo::all()->first()->fechaInicio), Carbon\Carbon::parse(App\Periodo::all()->first()->fechaFinal));
	return view('welcome', ['periodoSistema' => $periodoSistema, 'esAccesible' => $esAccesible]);
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/main', 'HomeController@main');

//////////// Estudiantes //////////////
// Crea todas las rutas para las funciones del controlador "Estudiantes"
Route::resource('/estudiantes', 'Estudiantes');
// Ruta para datos del formulario de estudiantes
Route::post('newEstudiante', 'Estudiantes@newEstudiante');
// Ruta para cargar el formulario para los estudiantes
Route::get('/formularioEstudiantes', 'Estudiantes@formulario');
// Ruta para descargar o visualizar los documentos del estudiante.
Route::get('/getDocumentos/{carpetaDocumentos}/{carpetaFechas}/{documentos}', 'Estudiantes@getDocumentos');
///////////////////////////////////////

//////////// Actividades //////////////
// Crea todas las rutas para las funciones del controlador "Actividades"
Route::resource('/actividades', 'Actividades');
Route::post('/setEstudianteElegido', 'Actividades@setEstudianteElegido');
Route::post('/eliminarEstudianteElegido', 'Actividades@eliminarEstudianteElegido');
//////////////////////////////////////

//////////// Areas //////////////
// Crea todas las rutas para las funciones del controlador "Areas"
Route::resource('/areas', 'Areas');
///////////////////////////////////////

 //////////// Bancos //////////////
 // Crea todas las rutas para las funciones del controlador "Bancos"
 Route::resource('/bancos', 'Bancos');
 ///////////////////////////////////////

 //////////// Carreras //////////////
 // Crea todas las rutas para las funciones del controlador "Carreras"
 Route::resource('/carreras', 'Carreras');
 ///////////////////////////////////////

// Ruta para actualizar las fechas de acceso al sistema
Route::put('actualizarPeriodo', 'Periodos@update');
///////////////////////////////////////

//////////////CARGAR ARCHIVOS DE EXCEL///////////////////
Route::post('importPromedio', 'ImportPromedios@importPromedio');

//////////////CARGAR ARCHIVOS DE EXCEL PARA NIVELES DE ESTUDIANTE///////////////////
Route::post('importNiveles', 'importNiveles@importNiveles');

//////////// Usuarios //////////////
// Crea todas las rutas para las funciones del controlador "Bancos"
Route::resource('/usuarios', 'Users');
Route::post('/usuarios/delete', 'Users@delete');
Route::post('/contrasena', 'HomeController@contrasena');
///////////////////////////////////////


// Ruta para limpiar la base de datos
Route::post('limpiarBase', 'GestionBD@clean');
 ///////////////////////////////////////

//////////// Temporal para template //////////////
// Crea todas las rutas para las funciones del controlador "Bancos"
// Route::get('/main', function(){
// 	return view('admin.main');
// });
Route::get("mail", function(){
	return view("estudiante.mail.template");
});
///////////////////////////////////////

///////////////////////Pdf///////////////////
Route::get('pdf/{id}', 'PdfController@invoice');

//////////NOTIFICACIONES////////////////////////
Route::get('deleteNotification', 'Notificaciones@destroy');

////////////////// Excel Reportes /////////////////
Route::get('reporteGeneral', 'Reportes@reporteGeneral');
Route::get('reporteEstudiantesSeleccionados', 'Reportes@reporteEstudiantesSeleccionados');

///////////////// Manual de usuario ////////////////
Route::get('manual', function(){
	return view('admin.manual.index');
});
Route::get('manual/actividades', function(){
	return view('admin.manual.secciones.actividades');
});
Route::get('manual/bancos', function(){
	return view('admin.manual.secciones.banco');
});
Route::get('manual/carreras', function(){
	return view('admin.manual.secciones.carreras');
});
Route::get('manual/estudiantes', function(){
	return view('admin.manual.secciones.estudiantes');
});
Route::get('manual/fecha', function(){
	return view('admin.manual.secciones.fecha');
});
Route::get('manual/usuarios', function(){
	return view('admin.manual.secciones.usuarios');
});
Route::get('manual/excel', function(){
	return view('admin.manual.secciones.subir');
});

resources/views/admin/actividades.blade.php
@extends('layouts.app')

@section('content')
<!-- Mensajes de alerta, en el controlador se llaman utilizando flash('mensaje') -->



      <form action="{{ route('actividades.store') }}" class="form-horizontal" method="POST" autocomplete="off" id="formularioActividad">
        <!-- token para formularios de Laravel -->
        {{ csrf_field() }}
        <!--  -->
        <div class="form-group form-group-sm @if($errors->has('ref')) has-error @endif">
          <label for="ref" class="control-label col-sm-3">Referencia:</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" name="ref" placeholder="Número de referencia de actividad o proyecto" value="{{ $nuevaRef }}" disabled required>
            @if($errors->has('ref'))
              <span class="help-block">{{ $errors->first('ref') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group form-group-sm">
          <label for="sigla" class="control-label col-sm-3">Sigla:</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" name="sigla" placeholder="Sigla de actividad o proyecto">
          </div>
        </div>
        <div class="form-group form-group-sm @if($errors->has('titulo')) has-error @endif	">
          <label for="titulo" class="control-label col-sm-3">Título:</label>
          <div class="col-sm-9">
            <input type="text" class="form-control" name="titulo" placeholder="Título de actividad o proyecto" required>
            @if($errors->has('titulo'))
              <span class="help-block">{{ $errors->first('titulo') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group form-group-sm @if($errors->has('horas')) has-error @endif">
          <label for="horas" class="control-label col-sm-3">Total de horas:</label>
          <div class="col-sm-9">
            <input type="number" class="form-control" name="horas" value="1" min="1" max="20" required>
            @if($errors->has('horas'))
              <span class="help-block">{{ $errors->first('horas') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group form-group-sm @if($errors->has('area')) has-error @endif">
          <label for="area" class="control-label col-sm-3">Área:</label>
          <div class="col-sm-9">
            <select class="form-control" name="area" required>
              @if(isset($areas))
              @if(count($areas) > 0)
              @foreach($areas as $area)
              <option value="{{ $area->id }}">{{ $area->nombre }}</option>
              @endforeach
              @endif
              @endif
            </select>
            @if($errors->has('area'))
              <span class="help-block">{{ $errors->first('area') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group form-group-sm @if($errors->has('tipo')) has-error @endif">
          <label for="tipo" class="control-label col-sm-3">Tipo:</label>
          <div class="col-sm-9">
            @if(isset($designaciones))
            @if(count($designaciones) > 0)
            @foreach($designaciones as $designacion)
            <label class="radio-inline">
              <input type="radio" name="tipo" value="{{ $designacion->id }}" required> {{ $designacion->nombre }}
            </label>
            @endforeach
            @endif
            @endif
            @if($errors->has('banco'))
              <span class="help-block">{{ $errors->first('tipo') }}</span>
            @endif
          </div>
        </div>
        <hr>
        <div class="form-group form-group-sm @if($errors->has('descrip')) has-error @endif">
          <label for="descrip" class="control-label col-sm-3">Descripción:</label>
          <div class="col-sm-9">
            <textarea class="form-control" name="descrip" placeholder="Descripción de actividad o proyecto" required></textarea>
            @if($errors->has('descrip'))
              <span class="help-block">{{ $errors->first('descrip') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group form-group-sm @if($errors->has('req')) has-error @endif">
          <label for="req" class="control-label col-sm-3">Requisitos:</label>
          <div class="col-sm-9">
            <textarea class="form-control" name="req" placeholder="Requisitos de actividad o proyecto" required></textarea>
            @if($errors->has('req'))
              <span class="help-block">{{ $errors->first('req') }}</span>
            @endif
          </div>
        </div>
        <hr>
        <div class="col-sm-offset-3">
          <button type="submit" class="btn btn-success btn-sm" id="boton_enviar">Agregar actividad</button>
        </div>
      </form>


@endsection

resources/views/admin/categorias.blade.php
@extends('layouts.app')
<script src="/js/jscolor.js"></script>
@section('content')
<!-- Mensajes de alerta, en el controlador se llaman utilizando flash('mensaje') -->
@if (session()->has('flash_notification.message'))
@endif
<div class="modal fade" id="modalAgregarCategoria" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="container">
          <div class="row">
            <form action="{{ route('categorias.store') }}" class="form-horizontal" method="POST" autocomplete="off" id="formularioCategoria" ng-controller="formularioCategoria">
              <!-- token para formularios de Laravel -->
              {{ csrf_field() }}
              <!--  -->
              <div class="form-group form-group-sm @if($errors->has('nombre')) has-error @endif">
                <label for="nombre" class="control-label col-sm-3">Nombre:</label>
                <div class="col-sm-9">
                  <input type="text" class="form-control" name="nombre" placeholder="Nombre de la área" required>
                  @if($errors->has('nombre'))
                  <span class="help-block">{{ $errors->first('nombre') }}</span>
                  @endif
                </div>
              </div>
              <div class="form-group form-group-sm @if($errors->has('color')) has-error @endif">
                <label for="color" class="control-label col-sm-3">Color:</label>
                <div class="col-sm-9">
                  <input type="text" class="form-control jscolor" name="color" value="41ADE7" placeholder="Color de la área" required>
                  @if($errors->has('color'))
                  <span class="help-block">{{ $errors->first('color') }}</span>
                  @endif
                </div>
              </div>

              <div class="col-sm-offset-3">
                <button type="submit" class="btn btn-success btn-sm" id="boton_enviar">Agregar área</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/main.blade.php
<!DOCTYPE html>
<html lang="es" ng-app="Horas">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}" />

  <!-- Styles -->
  <link href="/css/app.css" rel="stylesheet" />
  <link rel="shortcut icon" type="image/x-icon" href="/img/ucr-favicon.png"/>
  <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css" />
  <link rel="stylesheet" type="text/css" href="/css/include/bootstrap-datetimepicker.min.css" />
  <link rel="stylesheet" type="text/css" href="{{ asset('css/include/trumbowyg.min.css') }}">

  <!-- Template custom styles -->
  <link rel="stylesheet" type="text/css" href="{{ asset('css/include/custom.min.css') }}">

  <!-- Scripts -->
  <script src = "/js/include/jquery.min.js"></script>
  <script src = "/js/include/angular.min.js"></script>
  <script src = "/js/include/dirPagination.js"></script>
  <script src = "/js/include/moment.min.js"></script>
  <script src = "/js/include/bootstrap.min.js"></script>
  <script src = "/js/include/bootstrap-datetimepicker.min.js"></script>
  <script src = "/js/include/trumbowyg.min.js"></script>
  <script src = "/js/include/es.js"></script>

  <script src= "/js/controllers/homeController.js"></script>
  <script src="/js/controllers/estudiante.js"></script>
  <script src = "/js/controllers/area.js"></script>
  <script src = "/js/controllers/actividad.js"></script>
  <script src = "/js/controllers/banco.js"></script>
  <script src = "/js/controllers/usuario.js"></script>
  <script src = "/js/controllers/carrera.js"></script>
  <script src = "/js/script.js"></script>

  <script>
    window.Laravel = <?php echo json_encode([
      'csrfToken' => csrf_token(),
      ]); ?>
  </script>

  <title>Horas estudiante y horas asistente</title>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="" class="site_title"><i class="fa fa-calendar-o" aria-hidden="true"></i> <span>HORAS</span></a>
            </div>

            <div class="clearfix"></div>


            <br />

            <!-- sidebar menu -->
            @include('admin.partials.sub.sideBar')
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        @include('admin.partials.sub.topNavigation')
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <!-- top tiles -->
          @include('admin.partials.sub.topData')
          <!-- /top tiles -->
          <br />
          <div class="row">

            @include('admin.partials.home')

          </div>
        </div>
        <!-- footer content -->
      </div>
    </div>
    <div class="fonNar"></div>
    <footer>
      <div class="pull-left">
        <img src="/img/firma-footer.png">
      </div>
      <div class="pull-right firmaHoras">
        <h5>&#169; UCR - Horas estudiante y horas asistente</h5>
      </div>
      <div class="clearfix"></div>
    </footer>

    <!-- Template custom script -->
    <script src="{{ asset('js/include/custom.min.js') }}"></script>
    <!--  -->

    <!-- Llama modal para cambiar periodos del sistema -->
    <!-- Llama modales para insertar promedios y niveles -->
    @include("admin.partials.modalesExcel")

    @if(auth()->user()->user_type == 1)
      @include("admin.partials.modalPeriodoSistema")

      <!-- Llama modal para limpiar base de datos -->
      @include("admin.partials.modalLimpiarBD")
    @endif
  </body>
  </html>