routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
	$log = new App\Log();
	$log->ip = $_SERVER['REMOTE_ADDR'];
	$log->userAgent = $_SERVER['HTTP_USER_AGENT'];
	$log->save();

	$periodoSistema = App\Periodo::all()->first();
	$esAccesible = Carbon\Carbon::now()->between(Carbon\Carbon::parse(App\Periodo::all()->first()->fechaInicio), Carbon\Carbon::parse(App\Periodo::all()->first()->fechaFinal));
	return view('welcome', ['periodoSistema' => $periodoSistema, 'esAccesible' => $esAccesible]);
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/main', 'HomeController@main');

//////////// Estudiantes //////////////
// Crea todas las rutas para las funciones del controlador "Estudiantes"
Route::resource('/estudiantes', 'Estudiantes');
// Ruta para datos del formulario de estudiantes
Route::post('newEstudiante', 'Estudiantes@newEstudiante');
// Ruta para cargar el formulario para los estudiantes
Route::get('/formularioEstudiantes', 'Estudiantes@formulario');
// Ruta para descargar o visualizar los documentos del estudiante.
Route::get('/getDocumentos/{carpetaDocumentos}/{carpetaFechas}/{documentos}', 'Estudiantes@getDocumentos');
///////////////////////////////////////

//////////// Actividades //////////////
// Crea todas las rutas para las funciones del controlador "Actividades"
Route::resource('/actividades', 'Actividades');
Route::post('/setEstudianteElegido', 'Actividades@setEstudianteElegido');
Route::post('/eliminarEstudianteElegido', 'Actividades@eliminarEstudianteElegido');
//////////////////////////////////////

//////////// Areas //////////////
// Crea todas las rutas para las funciones del controlador "Areas"
Route::resource('/areas', 'Areas');
///////////////////////////////////////

 //////////// Bancos //////////////
 // Crea todas las rutas para las funciones del controlador "Bancos"
 Route::resource('/bancos', 'Bancos');
 ///////////////////////////////////////

 //////////// Carreras //////////////
 // Crea todas las rutas para las funciones del controlador "Carreras"
 Route::resource('/carreras', 'Carreras');
 ///////////////////////////////////////

// Ruta para actualizar las fechas de acceso al sistema
Route::put('actualizarPeriodo', 'Periodos@update');
///////////////////////////////////////

//////////////CARGAR ARCHIVOS DE EXCEL///////////////////
Route::post('importPromedio', 'ImportPromedios@importPromedio');

//////////////CARGAR ARCHIVOS DE EXCEL PARA NIVELES DE ESTUDIANTE///////////////////
Route::post('importNiveles', 'importNiveles@importNiveles');

//////////// Usuarios //////////////
// Crea todas las rutas para las funciones del controlador "Bancos"
Route::resource('/usuarios', 'Users');
Route::post('/usuarios/delete', 'Users@delete');
Route::post('/contrasena', 'HomeController@contrasena');
///////////////////////////////////////


// Ruta para limpiar la base de datos
Route::post('limpiarBase', 'GestionBD@clean');
 ///////////////////////////////////////

//////////// Temporal para template //////////////
// Crea todas las rutas para las funciones del controlador "Bancos"
// Route::get('/main', function(){
// 	return view('admin.main');
// });
Route::get("mail", function(){
	return view("estudiante.mail.template");
});
///////////////////////////////////////

///////////////////////Pdf///////////////////
Route::get('pdf/{id}', 'PdfController@invoice');

//////////NOTIFICACIONES////////////////////////
Route::get('deleteNotification', 'Notificaciones@destroy');

////////////////// Excel Reportes /////////////////
Route::get('reporteGeneral', 'Reportes@reporteGeneral');
Route::get('reporteEstudiantesSeleccionados', 'Reportes@reporteEstudiantesSeleccionados');

///////////////// Manual de usuario ////////////////
Route::get('manual', function(){
	return view('admin.manual.index');
});
Route::get('manual/actividades', function(){
	return view('admin.manual.secciones.actividades');
});
Route::get('manual/bancos', function(){
	return view('admin.manual.secciones.banco');
});
Route::get('manual/carreras', function(){
	return view('admin.manual.secciones.carreras');
});
Route::get('manual/estudiantes', function(){
	return view('admin.manual.secciones.estudiantes');
});
Route::get('manual/fecha', function(){
	return view('admin.manual.secciones.fecha');
});
Route::get('manual/usuarios', function(){
	return view('admin.manual.secciones.usuarios');
});
Route::get('manual/excel', function(){
	return view('admin.manual.secciones.subir');
});

app/Carrera.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Carrera extends Model
{
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre', 'sigla',
    ];

    // Relacion con estudiante
    public function estudiante()
    {
    	return $this->hasMany('App\Estudiante');
    }
}

app/Http/Controllers/Carreras.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Carrera;

use App\Estudiante;

class Carreras extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin');
        $this->middleware('userActivo');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nombre' => 'required|max:100',
            'sigla'  => 'required|max:20',
            ]);

        $carrera         = new Carrera();
        $carrera->nombre = $request->nombre;
        $carrera->sigla  = $request->sigla;

        if ($carrera->save()) {
            flash('Carrera guardada exitosamente.', 'success'); // Si no se guarda despliega esta alerta
        } else {
            flash('Error al guardar los datos.', 'danger'); // Si no se guarda despliega esta alerta
        }
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nombre' => 'required|max:100',
            'sigla'  => 'required|max:20',
            ]);

        $carrera         = Carrera::find($id);
        $carrera->nombre = $request->nombre;
        $carrera->sigla  = $request->sigla;

        if ($carrera->save()) {
            flash('Carrera actualizada exitósamente.', 'success'); // Si no se guarda despliega esta alerta
        } else {
            flash('Error al modificar los datos.', 'danger'); // Si no se guarda despliega esta alerta
        }
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $existe = Estudiante::where('fkCarrera', '=', $id)->first();
        if(isset($existe))
        {
            flash('Esta carrera tiene estudiantes relacionadas, elimine primero los estudiantes para poder realizar la acción.', 'danger');
            return back();
        }
        if(Carrera::destroy($id)){
            flash('Carrera eliminada exitosamente.', 'success'); // Si no se guarda despliega esta alerta
        } else {
            flash('Error al eliminar los datos.', 'danger'); // Si no se guarda despliega esta alerta
        }
        return back();
    }
}

resources/views/admin/carreras/modalesCarreras.blade.php
<!-- MODAL AGREGAR CARERA -->
<div class="modal fade" id="modalAgregarCarrera" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Agregar nueva carrera</h4>
            </div>
            <div class="modal-body">
                <form action="{{ route('carreras.store') }}" class="form-horizontal" method="POST" autocomplete="off" id="formularioCarrera" name="formAgregarCarrera">
                    <!-- token para formularios de Laravel -->
                {{ csrf_field() }}
                <!--  -->
                    <div class="form-group form-group-sm @if($errors->has('nombre')) has-error @endif">
                        <label for="nombre" class="control-label col-sm-3">Nombre:</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="nombre" placeholder="Nombre de la carrera" required>
                            <span style="color:red" ng-show="formAgregarCarrera.nombre.$dirty && formAgregarCarrera.nombre.$invalid">
                                <span class="error" ng-show="formAgregarCarrera.nombre.$error.required">El nombre de la carrera es requerido</span>
                            </span>
                            @if($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group form-group-sm @if($errors->has('sigla')) has-error @endif">
                        <label for="sigla" class="control-label col-sm-3">Sigla:</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="sigla" placeholder="Sigla de la carrera" required>
                            <span style="color:red" ng-show="formAgregarCarrera.sigla.$dirty && formAgregarCarrera.sigla.$invalid">
                                <span class="error" ng-show="formAgregarCarrera.sigla.$error.required">El sigla de la carrera es requerido</span>
                            </span>
                            @if($errors->has('sigla'))
                                <span class="help-block">{{ $errors->first('sigla') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-success btn-sm" ng-disabled="formAgregarCarrera.$invalid" ng-class="{disabled: formAgregarCarrera.$invalid}">Agregar carrera</button>
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
                    </div>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

<!-- MODAL MODIFICAR BANCO -->
<div class="modal fade" id="modalModificarCarrera" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modificar carrera</h4>
            </div>
            <div class="modal-body">
                <form action="@{{ 'carreras/' + modificarCarreraID }}" class="form-horizontal" method="POST" autocomplete="off" id="formularioModificarCarrera" name="formModificarCarrera">
                    <!-- token para formularios de Laravel -->
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="PUT">
                <!--  -->
                    <div class="form-group form-group-sm @if($errors->has('nombre')) has-error @endif">
                        <label for="nombre" class="control-label col-sm-3">Nombre:</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control validate" name="nombre" placeholder="Nombre de la carrear" ng-model="modificarNombreCarrera" required>
                            <span style="color:red" ng-show="formModificarCarrera.nombre.$dirty && formModificarCarrera.nombre.$invalid">
                                <span class="error" ng-show="formModificarCarrera.nombre.$error.required">El nombre de la carrera es requerido</span>
                            </span>
                            @if($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group form-group-sm @if($errors->has('sigla')) has-error @endif">
                        <label for="sigla" class="control-label col-sm-3">Sigla:</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" ng-model="modificarSiglaCarrera" name="sigla" placeholder="Sigla de la carrera" required>
                            <span style="color:red" ng-show="formAgregarCarrera.sigla.$dirty && formAgregarCarrera.sigla.$invalid">
                                <span class="error" ng-show="formAgregarCarrera.sigla.$error.required">El sigla de la carrera es requerido</span>
                            </span>
                            @if($errors->has('sigla'))
                                <span class="help-block">{{ $errors->first('sigla') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-warning btn-sm" id="boton_enviar" ng-disabled="formModificarCarrera.$invalid" ng-class="{disabled: formModificarCarrera.$invalid}">Modificar carrera</button>
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
                    </div>
                </form>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

resources/views/admin/carreras/tablaCarreras.blade.php
<div ng-controller="carreraCtrl">
 <!-- contenedor -->
 <div class="col-lg-4 col-md-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Carreras <br><small>Lista de carreras</small></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-sort" aria-hidden="true"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <a ng-click="myOrderBy('nombre')">Nombre</a> 
            </li>
            <li>
              <a ng-click="myOrderBy('sigla')">Sigla</a> 
            </li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <div class="dashboard-widget-content">
        <div class="col-xs-12">


          <div class="table-responsive center-block" id="nombreBancos">
            <br>
            <table class="table table-hover table-bordered">
              <thead>
                <tr>
                  <th id="thNom">Nombre de la carrera</th>
                  <th>Sigla</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr ng-repeat="carrera in carreras | orderBy : orderCarrera">
                  <td>@{{carrera.nombre}}</td>
                  <td>@{{carrera.sigla}}</td>
                  <td>
                    <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalModificarCarrera" ng-click="cargarModalModificarCarrera(carrera.id, carrera.nombre, carrera.sigla)">
                      <i class="fa fa-pencil" aria-hidden="true"></i>
                    </button>
                    <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalEliminar" ng-click="eliminarCarrera(carrera.id, carrera.nombre)"><i class="fa fa-trash" aria-hidden="true"></i></button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <!-- <button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#modalAgregarBanco">Agregar
            <i class="fa fa-plus" aria-hidden="true"></i>
          </button> -->


        </div>
        <!-- <div id="world-map-gdp" class="col-md-8 col-sm-12 col-xs-12" style="height:230px;"></div> -->
      </div>
    </div>
  </div>
</div>
<!-- Fin de contenedor -->
@include('admin.carreras.modalesCarreras')
</div>