routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
	$log = new App\Log();
	$log->ip = $_SERVER['REMOTE_ADDR'];
	$log->userAgent = $_SERVER['HTTP_USER_AGENT'];
	$log->save();

	$periodoSistema = App\Periodo::all()->first();
	$esAccesible = Carbon\Carbon::now()->between(Carbon\Carbon::parse(App\Periodo::all()->first()->fechaInicio), Carbon\Carbon::parse(App\Periodo::all()->first()->fechaFinal));
	return view('welcome', ['periodoSistema' => $periodoSistema, 'esAccesible' => $esAccesible]);
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/main', 'HomeController@main');

//////////// Estudiantes //////////////
// Crea todas las rutas para las funciones del controlador "Estudiantes"
Route::resource('/estudiantes', 'Estudiantes');
// Ruta para datos del formulario de estudiantes
Route::post('newEstudiante', 'Estudiantes@newEstudiante');
// Ruta para cargar el formulario para los estudiantes
Route::get('/formularioEstudiantes', 'Estudiantes@formulario');
// Ruta para descargar o visualizar los documentos del estudiante.
Route::get('/getDocumentos/{carpetaDocumentos}/{carpetaFechas}/{documentos}', 'Estudiantes@getDocumentos');
///////////////////////////////////////

//////////// Actividades //////////////
// Crea todas las rutas para las funciones del controlador "Actividades"
Route::resource('/actividades', 'Actividades');
Route::post('/setEstudianteElegido', 'Actividades@setEstudianteElegido');
Route::post('/eliminarEstudianteElegido', 'Actividades@eliminarEstudianteElegido');
//////////////////////////////////////

//////////// Areas //////////////
// Crea todas las rutas para las funciones del controlador "Areas"
Route::resource('/areas', 'Areas');
///////////////////////////////////////

 //////////// Bancos //////////////
 // Crea todas las rutas para las funciones del controlador "Bancos"
 Route::resource('/bancos', 'Bancos');
 ///////////////////////////////////////

 //////////// Carreras //////////////
 // Crea todas las rutas para las funciones del controlador "Carreras"
 Route::resource('/carreras', 'Carreras');
 ///////////////////////////////////////

// Ruta para actualizar las fechas de acceso al sistema
Route::put('actualizarPeriodo', 'Periodos@update');
///////////////////////////////////////

//////////////CARGAR ARCHIVOS DE EXCEL///////////////////
Route::post('importPromedio', 'ImportPromedios@importPromedio');

//////////////CARGAR ARCHIVOS DE EXCEL PARA NIVELES DE ESTUDIANTE///////////////////
Route::post('importNiveles', 'importNiveles@importNiveles');

//////////// Usuarios //////////////
// Crea todas las rutas para las funciones del controlador "Bancos"
Route::resource('/usuarios', 'Users');
Route::post('/usuarios/delete', 'Users@delete');
Route::post('/contrasena', 'HomeController@contrasena');
///////////////////////////////////////


// Ruta para limpiar la base de datos
Route::post('limpiarBase', 'GestionBD@clean');
 ///////////////////////////////////////

//////////// Temporal para template //////////////
// Crea todas las rutas para las funciones del controlador "Bancos"
// Route::get('/main', function(){
// 	return view('admin.main');
// });
Route::get("mail", function(){
	return view("estudiante.mail.template");
});
///////////////////////////////////////

///////////////////////Pdf///////////////////
Route::get('pdf/{id}', 'PdfController@invoice');

//////////NOTIFICACIONES////////////////////////
Route::get('deleteNotification', 'Notificaciones@destroy');

////////////////// Excel Reportes /////////////////
Route::get('reporteGeneral', 'Reportes@reporteGeneral');
Route::get('reporteEstudiantesSeleccionados', 'Reportes@reporteEstudiantesSeleccionados');

///////////////// Manual de usuario ////////////////
Route::get('manual', function(){
	return view('admin.manual.index');
});
Route::get('manual/actividades', function(){
	return view('admin.manual.secciones.actividades');
});
Route::get('manual/bancos', function(){
	return view('admin.manual.secciones.banco');
});
Route::get('manual/carreras', function(){
	return view('admin.manual.secciones.carreras');
});
Route::get('manual/estudiantes', function(){
	return view('admin.manual.secciones.estudiantes');
});
Route::get('manual/fecha', function(){
	return view('admin.manual.secciones.fecha');
});
Route::get('manual/usuarios', function(){
	return view('admin.manual.secciones.usuarios');
});
Route::get('manual/excel', function(){
	return view('admin.manual.secciones.subir');
});

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre', 'color',
    ];

	// Relacion con actividad
    public function actividad()
    {
    	return $this->hasMany('App\Atividad');
    }

    // Relacion con User
    public function users()
    {
        return $this->hasMany('App\User');
    }

    public function rel_area_users()
    {
        return $this->belongsToManny('App\RelAreaUser');
    }
}

app/Http/Controllers/Areas.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

//Modelos
use App\Area;
use App\RelAreaUser;
use App\Actividad;

class Areas extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin');
        $this->middleware('userActivo');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.areas');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nombre'     => 'required|max:200',
            'color'    => 'required|max:10',
            ]);

        // Se crea un instancia del modelo
        $area = new Area();
        // Se asignan valores a la area
        $area->nombre  = $request->nombre;
        $area->color = $request->color;

        // Se guardan los datos de la area en la base de datos
        if(!$area->save())
        {
          flash('Error al guardar los datos.', 'danger'); // Si no se guarda despliega esta alerta
          return back();
        }
        else
        {
          flash('Área guardada exitosamente.', 'success');
          return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $area = Area::find($id);
        return view('admin.editarAreas')->with(['area' => $area]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
          'nombre'     => 'required|max:200',
          'color'    => 'required|max:10',
          ]);

      $area = Area::find($id);

      $area->nombre  = $request->nombre;
      $area->color = $request->color;

      if(!$area->save())
      {
        flash('Error al actualizar los datos.', 'danger'); // Si no se guarda despliega esta alerta
        return back();
      }
      else
      {
        flash('Área actualizada exitósamente.', 'success');
      }
      // Retorna
      return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $existe = Actividad::where('fkArea', '=', $id)->first();
        if(isset($existe))
        {
            flash('Esta área tiene actividades relacionadas, elimine primero las actividades para poder realizar la acción.', 'danger');
            return back();
        }


        $query = \DB::table('rel_area_users')->where('area', '=', $id)->get();
        if (count($query) > 0) {
            flash('Esta área tiene usuarios de actividades registrados, por lo tanto no se puede eliminar. Verifique los usuarios y elimine los que están asignados a esta área para poder realizar esta acción.', 'danger');
            return back();
        }

        if (Area::destroy($id)) {
            flash('Área eliminada exitósamente.', 'success');
        } else {
            flash('Error al eliminar los datos.', 'danger');
        }

        return back();
    }
}

resources/views/admin/areas/modalesArea.blade.php
<div class="modal fade" id="modalModificarArea" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modificar área de la actividad</h4>
      </div>
      <div class="modal-body">
        <form action="@{{ 'areas/'+ modificarAreaID }}" class="form-horizontal" method="POST" autocomplete="off" id="formularioArea">
          <!-- token para formularios de Laravel -->
          {{ csrf_field() }}
          <!--  -->
          <!-- Método de envío -->
            <input type="hidden" name="_method" value="PUT">
          <!--  -->
          <div class="form-group form-group-sm @if($errors->has('nombre')) has-error @endif">
            <label for="nombre" class="control-label col-sm-3">Nombre:</label>
            <div class="col-sm-9">
            <input type="text" class="form-control" name="nombre" placeholder="Nombre del área" ng-model="modificarNombreArea" required>
              @if($errors->has('nombre'))
              <span class="help-block">{{ $errors->first('nombre') }}</span>
              @endif
            </div>
          </div>
          <div class="form-group form-group-sm @if($errors->has('color')) has-error @endif">
            <label for="color" class="control-label col-sm-3">Color:</label>
            <div class="col-sm-9">
              <input type="color" class="form-control jscolor" name="color" placeholder="Color del área" ng-model="modificarColorArea" required>
              @if($errors->has('color'))
              <span class="help-block">{{ $errors->first('color') }}</span>
              @endif
            </div>
          </div>

          <div class="pull-right">
            <button type="submit" ng-disabled="!modificarNombreArea" class="btn btn-warning btn-sm" id="boton_enviar">Modificar área</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
          </div>
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

<!-- MODAL AGREGAR AREA -->
<div class="modal fade" id="modalAgregarArea" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Agregar nueva área</h4>
      </div>
      <div class="modal-body">
        <form action="{{ route('areas.store') }}" class="form-horizontal" method="POST" autocomplete="off" id="formularioArea">
              <!-- token para formularios de Laravel -->
              {{ csrf_field() }}
              <!--  -->
              <div class="form-group form-group-sm @if($errors->has('nombre')) has-error @endif">
                <label for="nombre" class="control-label col-sm-3">Nombre:</label>
                <div class="col-sm-9">
                  <input type="text" class="form-control" name="nombre" placeholder="Nombre del área" ng-model="someText" required>
                  @if($errors->has('nombre'))
                  <span class="help-block">{{ $errors->first('nombre') }}</span>
                  @endif
                </div>
              </div>
            <div class="form-group form-group-sm @if($errors->has('color')) has-error @endif">
                <label for="color" class="control-label col-sm-3">Color:</label>
                <div class="col-sm-9">
                  <input type="color" class="form-control" name="color" value="#2095f2" placeholder="Color del area" required>
                  @if($errors->has('color'))
                  <span class="help-block">{{ $errors->first('color') }}</span>
                  @endif
                </div>
              </div>

              <div class="pull-right">
                <button ng-disabled="!someText" type="submit" class="btn btn-success btn-sm" id="boton_enviar">Agregar área</button>
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
              </div>
            </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>

resources/views/admin/areas/tablaAreas.blade.php
<div ng-controller="areasCtrl">


  <!-- contenedor -->

  <div class="col-lg-4 col-md-6 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Áreas de actividades y/o proyectos <br class=""> <small>Lista de áreas</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-sort" aria-hidden="true"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a ng-click="myOrderBy('nombre')">Nombre</a>
              </li>
              <li><a ng-click="myOrderBy('color')">Color</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="dashboard-widget-content">
          <div class="col-xs-12">


            <div class="table-responsive center-block" id="infoEstudiantes">
              <br>
              <table class="table table-hover table-bordered">
                <thead>
                  <tr>
                    <th id="thNom">Nombre</th>
                    <th></th>
                    <th id="thPro"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr ng-repeat="area in areas | orderBy : orderArea">
                    <td>@{{area.nombre}}</td>
                    <td><i class="fa fa-tag" aria-hidden="true" style="color: @{{area.color}}"></i></td>
                    <td>
                      <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalModificarArea" ng-click="cargarModalModificar(area.id, area.nombre, area.color)">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                      </button>
                      <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalEliminar" ng-click="eliminarArea(area.id, area.nombre)"><i class="fa fa-trash" aria-hidden="true"></i></button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <!-- <button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#modalAgregarArea">Agregar
              <i class="fa fa-plus" aria-hidden="true"></i>
            </button> -->


          </div>
          <!-- <div id="world-map-gdp" class="col-md-8 col-sm-12 col-xs-12" style="height:230px;"></div> -->
        </div>
      </div>
    </div>
  </div>
  <!-- Fin de contenedor -->



  @include("admin.areas.modalesArea")
</div>